FROM nvidia/cuda-11.8.0-cudnn8-devel-ubuntu22.04

RUN apt-get -y update && apt-get -y install \
    ssh \
    sudo \
    git \
    make \
    build-essential \
    wget \
    libssl-dev \
    ca-certificates

ENV TZ=Asia/Seoul
RUN sudo ln -snf /usr/share/zoneinfo/$TZ /etc/localtime

RUN mkdir src
WORKDIR /src